sudo: required
dist: precise
language: cpp

perl:
  - 5.18

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - CXX_COMPILER=g++-4.9
        - CC_COMPILER=gcc-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        CXX_COMPILER=g++-5
        CC_COMPILER=gcc-5
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        CXX_COMPILER=g++-6
        CC_COMPILER=gcc-6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env:
        CXX_COMPILER=clang++-3.6
        CC_COMPILER=clang-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env:
        CXX_COMPILER=clang++-3.7
        CC_COMPILER=clang-3.7
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      env:
        CXX_COMPILER=clang++-3.8
        CC_COMPILER=clang-3.8
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
          packages:
            - clang-3.9
      env:
        CXX_COMPILER=clang++-3.9
        CC_COMPILER=clang-3.9

script: 
  - $CXX_COMPILER --version
  - $CC_COMPILER --version
  - make CXX=$CXX_COMPILER CC=$CC_COMPILER testex
